version: '3'

services:
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: stayhalo

  redis:
    image: redis:6.2.5-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - ./redis:/data